# Generated by Django 6.0.1 on 2026-01-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_create_curriculumday_tools_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True, help_text='What this tool is used for'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='download_url',
            field=models.URLField(blank=True, help_text='Link to download or learn more'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome class, e.g., 'fab fa-figma'", max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Custom icon image', null=True, upload_to='tool_icons/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Is this tool required or optional?'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(help_text='e.g., Figma, Photoshop', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        # migrations.DeleteModel(
        #     name='CurriculumDay_tools',
        # ),
    ]
