# Generated by Django 6.0.1 on 2026-01-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_video_thumbnail_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumday',
            options={'ordering': ['course', 'order', 'day_number']},
        ),
        migrations.AlterField(
            model_name='curriculumday',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curriculumday',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curriculumday',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='curriculumday',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='curriculum_days', to='lms.tool'),
        ),
    ]
