# Generated by Django 6.0.1 on 2026-01-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_curriculumday_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='tools_needed',
            field=models.ManyToManyField(blank=True, related_name='videos', to='lms.tool'),
        ),
    ]
