# Generated by Django 6.0.1 on 2026-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_video_duration_alter_video_tools_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, editable=False, help_text='Automatically calculated video duration', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='tools_needed',
            field=models.ManyToManyField(blank=True, help_text='Tools required for this video', related_name='videos', to='lms.tool'),
        ),
    ]
