# Generated by Django 6.0.1 on 2026-02-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, editable=False, help_text='Automatically calculated video duration', null=True),
        ),
    ]
