# Generated by Django 6.0.1 on 2026-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_auto_20260212_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brochure',
            field=models.FileField(blank=True, help_text='Upload course brochure/syllabus PDF', null=True, upload_to='course_brochures/'),
        ),
    ]
