# Generated by Django 6.0.1 on 2026-02-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_alter_course_brochure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
    ]
