# Generated by Django 6.0.1 on 2026-02-17 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_video_duration_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_session_id',
            new_name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
