# Generated by Django 6.0.1 on 2026-02-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube / Vimeo / external video URL'),
        ),
    ]
