# Generated by Django 6.0.1 on 2026-02-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetool',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursetool',
            name='download_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coursetool',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coursetool',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='tool_icons/'),
        ),
        migrations.AddField(
            model_name='coursetool',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
