# Generated by Django 6.0.1 on 2026-02-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_coursetool_description_coursetool_download_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetool',
            options={},
        ),
    ]
