# Generated by Django 6.0.1 on 2026-02-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_alter_coursetool_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetool',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='coursetool',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coursetool',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='coursetool',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='coursetool',
            name='icon_image',
        ),
        migrations.RemoveField(
            model_name='coursetool',
            name='is_required',
        ),
        migrations.AddField(
            model_name='coursetool',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
