# Generated by Django 6.0.1 on 2026-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_alter_coursetool_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetool',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
